import Stripe from 'stripe';

// Initialize Stripe with your secret key
const stripe = new Stripe(process.env.STRIPE_SECRET_KEY, { apiVersion: '2020-08-27' });

export default async function handler(req, res) {
  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  // Get the token and amount from the request body
  const { token, amount } = req.body;

  // Validate that both token and amount are present
  if (!token || !amount) {
    return res.status(400).json({ error: 'Missing required fields' });
  }

  try {
    // Create a charge using the Stripe API
    const charge = await stripe.charges.create({
      amount,  // The amount to charge in the smallest currency unit (e.g., cents)
      currency: 'gbp',  // The currency to charge in (adjust as needed)
      description: 'Booking payment',  // Description for the charge
      source: token,  // The payment source, which is the token generated by Stripe
    });

    // Send success response back to the client
    return res.status(200).json({ message: 'Payment successful', charge });
  } catch (error) {
    console.error(error);
    // Send error response in case of failure
    return res.status(500).json({ error: 'Payment processing failed' });
  }
}
